### ISSUE TITLE
add mimikatz

### ISSUE THREAD

**Issue by MrAle98** [sliverarmory/armory#34]
I've decided to modify mimikatz in order to be loaded as a DLL inside sliver implant. Here the repository: https://github.com/MrAle98/mimikatz. Open the project in visual studio 2019 and use **sliverkatz** build type in order to produce **powerkatz.dll**.

Here it is a screenshot of running dll powerkatz.dll in a sliver implant:
![image](https://github.com/sliverarmory/armory/assets/74059030/d6a5218a-85ee-48ba-9bf7-134a0cfe9f14)

**Comment by unkn0wnsyst3m** [comment]
while this is waiting for an implementation, @MrAle98 can you list here what you do after you build the DLL?

**Comment by MrAle98** [comment]
@unkn0wnsyst3m yeah sure. Go under ~/.sliver-client/extensions/, create directory called mimikatz, inside the directory copy sliverkatz.dll and rename it mimikatz.dll, copy also extension.json under same directory. Now start sliver, get a beacon/session and you should have the mimikatz command available. Let me know in case you have issues.

**Comment by n3rada** [comment]
How does the process of adding to the official `sliver` armory work? What's needed to integrate a request like this one?

**Comment by moloch--** [comment]
I think we need to fork and update the index, @c2biz if you have some time can you take care of this one.

**Comment by lesnuages** [comment]
We would also need to automate the build with a GitHub action.

**Comment by c2biz** [comment]
Added in #54
