### ISSUE TITLE
Synchronisation required for `rubeus` which fixes problems when running as `LocalSystem`.

### ISSUE THREAD

**Issue by n3rada** [sliverarmory/armory#53]
Hi @c2biz,

I really like the `rubeus` integration.

Is it possible to sync the main repo for the [sliver fork](https://github.com/sliverarmory/Rubeus) in order to correct an important bug from [this](https://github.com/GhostPack/Rubeus/pull/188) merged PR? 

For more explanations, please refer to [this](https://github.com/GhostPack/Rubeus/issues/184) issue.

Thanks a lot

**Comment by c2biz** [comment]
https://github.com/sliverarmory/Rubeus/releases/tag/v0.0.24
