### ISSUE TITLE
TGTdeleg extension request

### ISSUE THREAD

**Issue by zimnyaa** [sliverarmory/armory#6]
Thought it would be a nice idea to add functionality akin to `rubeus tgtdeleg` without remote process injection.

https://github.com/connormcgarr/tgtdelegation seems like a great fit, and I've tested that it works out-of-the-box with COFF here:

https://github.com/zimnyaa/tgtdeleg

**Comment by c2biz** [comment]
Sliver support for this tool has been implemented: https://github.com/sliverarmory/armory/blob/master/armory.json#L547
