### ISSUE TITLE
Import probe BOF

### ISSUE THREAD

**Issue by rwhitcroft** [sliverarmory/armory#7]
Can we bring in the `probe` BOF from CS-Situational-Awareness-BOF?
Cheers!

**Comment by moloch--** [comment]
Can you link to the repo?

**Comment by c2biz** [comment]
This one? https://github.com/trustedsec/CS-Situational-Awareness-BOF/tree/master/src/SA/probe

**Comment by rwhitcroft** [comment]
Should have linked originally, sorry. Yes that's it, thanks c2biz.

**Comment by moloch--** [comment]
Oh yea, just need to finish porting the SA BOFs, this is on the agenda, I've just been busy :)

**Comment by c2biz** [comment]
Added - https://github.com/sliverarmory/CS-Situational-Awareness-BOF/releases/download/v0.0.21/sa-probe.tar.gz
